version: "3.7"

services:
  express:
    container_name: "express"
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    command: "npm run dev"
    volumes:
      - ../../:/app
    ports:
      - "3000:3000"